[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m integration.high_availability.conftest:conftest.py:68 Deploying mysql-k8s and scaling to 3 units
[32mINFO    [0m juju.model:model.py:2098 Deploying local:mysql-k8s-0
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [allocating] waiting: installing agent
  mysql-k8s/1 [allocating] waiting: installing agent
  mysql-k8s/2 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [executing] maintenance: Initialising mysqld
  mysql-k8s/1 [executing] maintenance: Initialising mysqld
  mysql-k8s/2 [executing] maintenance: Initialising mysqld
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [executing] waiting: waiting to join the cluster
  mysql-k8s/2 [idle] maintenance: joining the cluster
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [executing] maintenance: joining the cluster
  mysql-k8s/2 [executing] active: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:71 Deploying mysql-test-app
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/mysql-test-app-63
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-test-app/0 [allocating] waiting: installing agent
[32mINFO    [0m integration.high_availability.conftest:conftest.py:74 Relating mysql-k8s with mysql-test-app
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [executing] active: 
  mysql-k8s/2 [executing] active: 
  mysql-test-app/0 [executing] waiting: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:29 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:31 Starting continuous writes
[32mINFO    [0m integration.conftest:conftest.py:20 Getting credentials for the MySQL cluster
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:400 Ensure there are 3 online mysql members
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:405 Ensure that all units have incrementing continuous writes
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:506 max_written_value=855 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:506 max_written_value=858 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:506 max_written_value=860 on unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:411 Get mysqld pids on all instances
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:419 Stopping mysqld on mysql-k8s/0
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:419 Stopping mysqld on mysql-k8s/1
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:419 Stopping mysqld on mysql-k8s/2
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:422 Wait until mysqld stopped on all instances
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:430 Starting mysqld on mysql-k8s/0
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:430 Starting mysqld on mysql-k8s/1
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:430 Starting mysqld on mysql-k8s/2
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:434 Block until all in maintenance/offline
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:440 Wait all members to recover
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [idle] maintenance: offline
  mysql-k8s/1 [idle] maintenance: offline
  mysql-k8s/2 [idle] maintenance: offline
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [idle] maintenance: offline
  mysql-k8s/1 [idle] maintenance: offline
  mysql-k8s/2 [idle] maintenance: offline
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [idle] maintenance: offline
  mysql-k8s/1 [idle] maintenance: offline
  mysql-k8s/2 [idle] maintenance: offline
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [idle] maintenance: offline
  mysql-k8s/1 [idle] maintenance: offline
  mysql-k8s/2 [idle] maintenance: offline
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [executing] active: 
  mysql-k8s/2 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: 
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:459 Ensure all units have incrementing continuous writes
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:506 max_written_value=13457 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:506 max_written_value=13459 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:506 max_written_value=13462 on unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.conftest:conftest.py:36 Clearing continuous writes
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.5    unsupported  01:40:42Z

App             Version                  Status  Scale  Charm           Channel      Rev  Address         Exposed  Message
mysql-k8s       8.0.37-0ubuntu0.22.04.3  active      3  mysql-k8s                      0  10.152.183.111  no       
mysql-test-app  0.0.2                    active      1  mysql-test-app  latest/edge   63  10.152.183.56   no       Last written value=9752

Unit               Workload  Agent  Address      Ports  Message
mysql-k8s/0*       active    idle   10.1.171.77         Primary
mysql-k8s/1        active    idle   10.1.171.75         
mysql-k8s/2        active    idle   10.1.171.76         
mysql-test-app/0*  active    idle   10.1.171.78         Last written value=9752

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-1: 01:37:37 ERROR unit.mysql-k8s/1.juju-log Failed to get cluster status for test_cluster
unit-mysql-k8s-1: 01:37:37 ERROR unit.mysql-k8s/1.juju-log Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-2: 01:37:38 ERROR unit.mysql-k8s/2.juju-log Failed to get cluster status for test_cluster
unit-mysql-k8s-2: 01:37:38 ERROR unit.mysql-k8s/2.juju-log Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-0: 01:37:38 ERROR unit.mysql-k8s/0.juju-log Failed to get cluster status for test_cluster
unit-mysql-k8s-0: 01:37:38 ERROR unit.mysql-k8s/0.juju-log Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-1: 01:37:40 ERROR unit.mysql-k8s/1.juju-log database-peers:2: Failed to get cluster status for test_cluster
unit-mysql-k8s-1: 01:37:40 ERROR unit.mysql-k8s/1.juju-log database-peers:2: Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-2: 01:37:40 ERROR unit.mysql-k8s/2.juju-log database-peers:2: Failed to get cluster status for test_cluster
unit-mysql-k8s-2: 01:37:40 ERROR unit.mysql-k8s/2.juju-log database-peers:2: Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-0: 01:37:40 ERROR unit.mysql-k8s/0.juju-log database-peers:2: Failed to get cluster status for test_cluster
unit-mysql-k8s-0: 01:37:40 ERROR unit.mysql-k8s/0.juju-log database-peers:2: Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-1: 01:37:42 ERROR unit.mysql-k8s/1.juju-log database-peers:2: Failed to get cluster status for test_cluster
unit-mysql-k8s-1: 01:37:42 ERROR unit.mysql-k8s/1.juju-log database-peers:2: Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-2: 01:37:42 ERROR unit.mysql-k8s/2.juju-log database-peers:2: Failed to get cluster status for test_cluster
unit-mysql-k8s-2: 01:37:42 ERROR unit.mysql-k8s/2.juju-log database-peers:2: Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-0: 01:37:43 ERROR unit.mysql-k8s/0.juju-log database-peers:2: Failed to get cluster status for test_cluster
unit-mysql-k8s-0: 01:37:43 ERROR unit.mysql-k8s/0.juju-log database-peers:2: Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-1: 01:38:36 ERROR unit.mysql-k8s/1.juju-log Failed to get cluster status for test_cluster
unit-mysql-k8s-1: 01:38:36 ERROR unit.mysql-k8s/1.juju-log Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-k8s-2: 01:38:36 ERROR unit.mysql-k8s/2.juju-log Failed to get cluster status for test_cluster
unit-mysql-k8s-2: 01:38:36 ERROR unit.mysql-k8s/2.juju-log Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 792, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 1932, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...