[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that max_connections is set to 100 on mysql-k8s/0
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that innodb_buffer_pool_size is set to 20971520 on mysql-k8s/0
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that innodb_buffer_pool_chunk_size is set to 1048576 on mysql-k8s/0
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that group_replication_message_cache_size is set to 134217728 on mysql-k8s/0
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that max_connections is set to 100 on mysql-k8s/1
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that innodb_buffer_pool_size is set to 20971520 on mysql-k8s/1
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that innodb_buffer_pool_chunk_size is set to 1048576 on mysql-k8s/1
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that group_replication_message_cache_size is set to 134217728 on mysql-k8s/1
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that max_connections is set to 100 on mysql-k8s/2
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that innodb_buffer_pool_size is set to 20971520 on mysql-k8s/2
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that innodb_buffer_pool_chunk_size is set to 1048576 on mysql-k8s/2
[32mINFO    [0m integration.test_charm:test_charm.py:341 Checking that group_replication_message_cache_size is set to 134217728 on mysql-k8s/2
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.4    unsupported  01:41:27Z

App        Version  Status  Scale  Charm      Channel  Rev  Address        Exposed  Message
mysql-k8s           active      3  mysql-k8s             0  10.152.183.34  no       

Unit          Workload  Agent  Address       Ports  Message
mysql-k8s/0   active    idle   10.1.245.212         
mysql-k8s/1   active    idle   10.1.245.214         
mysql-k8s/2*  active    idle   10.1.245.213         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-2: 01:30:21 ERROR unit.mysql-k8s/2.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:30:23 ERROR unit.mysql-k8s/2.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:30:23 ERROR unit.mysql-k8s/1.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:30:25 ERROR unit.mysql-k8s/2.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:30:25 ERROR unit.mysql-k8s/1.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:30:27 ERROR unit.mysql-k8s/2.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:30:27 ERROR unit.mysql-k8s/1.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:30:29 ERROR unit.mysql-k8s/2.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:30:29 ERROR unit.mysql-k8s/1.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:30:31 ERROR unit.mysql-k8s/2.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:30:31 ERROR unit.mysql-k8s/1.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:30:44 ERROR unit.mysql-k8s/2.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:30:46 ERROR unit.mysql-k8s/1.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:30:46 ERROR unit.mysql-k8s/2.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:30:48 ERROR unit.mysql-k8s/1.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:30:48 ERROR unit.mysql-k8s/2.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:30:53 ERROR unit.mysql-k8s/0.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:30:55 ERROR unit.mysql-k8s/0.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:31:13 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:31:15 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:31:17 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:31:20 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:31:22 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:31:24 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:31:39 ERROR unit.mysql-k8s/1.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:31:39 ERROR unit.mysql-k8s/0.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:31:41 ERROR unit.mysql-k8s/1.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:31:41 ERROR unit.mysql-k8s/0.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:31:43 ERROR unit.mysql-k8s/1.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:31:43 ERROR unit.mysql-k8s/0.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:32:54 ERROR unit.mysql-k8s/3.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:32:56 ERROR unit.mysql-k8s/3.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:32:58 ERROR unit.mysql-k8s/3.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-4: 01:32:58 ERROR unit.mysql-k8s/4.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:33:00 ERROR unit.mysql-k8s/3.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-4: 01:33:00 ERROR unit.mysql-k8s/4.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:33:02 ERROR unit.mysql-k8s/3.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-4: 01:33:02 ERROR unit.mysql-k8s/4.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:33:04 ERROR unit.mysql-k8s/3.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-4: 01:33:04 ERROR unit.mysql-k8s/4.juju-log database-peers:0: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-4: 01:33:54 ERROR unit.mysql-k8s/4.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-4: 01:33:56 ERROR unit.mysql-k8s/4.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:33:57 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-4: 01:33:58 ERROR unit.mysql-k8s/4.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:17 ERROR unit.mysql-k8s/3.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:19 ERROR unit.mysql-k8s/3.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:21 ERROR unit.mysql-k8s/3.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:37:25 ERROR unit.mysql-k8s/1.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-1: 01:37:27 ERROR unit.mysql-k8s/1.juju-log get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:37:55 ERROR unit.mysql-k8s/2.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 723, in _run_mysqlsh_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@mysql-k8s-2.mysql-k8s-endpoints.testing.svc.cluster.local:33062', '--python', '--verbose=0', '-c', "shell.options.set('useWizards', False)\nprint('###')\nshell.connect_to_primary()\nprimary_address = shell.parse_uri(session.uri)['host']\nprint(f'<PRIMARY_ADDRESS>{primary_address}</PRIMARY_ADDRESS>')"], stdout="\x1b[1mPlease provide the password for 'serverconfig@mysql-k8s-2.mysql-k8s-endpoints.testing.svc.cluster.local:33062': \x1b[0m###\n", stderr='Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory\nTraceback (most recent call last):\n  File "<string>", line 3, in <module>\nmysqlsh.Error: Shell Error (51104): Shell.connect_to_primary: Metadata for instance 23e0709b-14e2-11f0-a026-666ed76bfab3 not found\n'
unit-mysql-k8s-1: 01:37:55 ERROR unit.mysql-k8s/1.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 723, in _run_mysqlsh_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@mysql-k8s-1.mysql-k8s-endpoints.testing.svc.cluster.local:33062', '--python', '--verbose=0', '-c', "shell.options.set('useWizards', False)\nprint('###')\nshell.connect_to_primary()\nprimary_address = shell.parse_uri(session.uri)['host']\nprint(f'<PRIMARY_ADDRESS>{primary_address}</PRIMARY_ADDRESS>')"], stdout="\x1b[1mPlease provide the password for 'serverconfig@mysql-k8s-1.mysql-k8s-endpoints.testing.svc.cluster.local:33062': \x1b[0m###\n", stderr='Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory\nTraceback (most recent call last):\n  File "<string>", line 3, in <module>\nmysqlsh.Error: Shell Error (51104): Shell.connect_to_primary: Metadata for instance 23e0709b-14e2-11f0-a026-666ed76bfab3 not found\n'
unit-mysql-k8s-2: 01:39:43 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:39:45 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...