{"uid":"26dd70d6830cc997","name":"test_graceful_full_cluster_crash_test","fullName":"tests.integration.high_availability.test_self_healing_stop_all#test_graceful_full_cluster_crash_test","historyId":"7d02ac8c8300bc817c84cf65fe597430","time":{"start":1756519598900,"stop":1756519961230,"duration":362330},"description":"Test to send SIGTERM to all units and then ensure that the cluster recovers.","descriptionHtml":"<p>Test to send SIGTERM to all units and then ensure that the cluster recovers.</p>\n","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7fa23d31c860 state=finished raised AssertionError>]","statusTrace":"Traceback (most recent call last):\n  File \"/root/spread_project/tests/integration/high_availability/test_self_healing_stop_all.py\", line 62, in test_graceful_full_cluster_crash_test\n    await ensure_process_not_running(\n  File \"/root/spread_project/tests/integration/high_availability/high_availability_helpers.py\", line 576, in ensure_process_not_running\n    assert return_code != 0, (\n           ^^^^^^^^^^^^^^^^\nAssertionError: Process mysqld is still running with pid 877\n on unit mysql-k8s/0, container mysql\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n                                ^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/root/spread_project/tests/integration/high_availability/test_self_healing_stop_all.py\", line 59, in test_graceful_full_cluster_crash_test\n    for attempt in Retrying(stop=stop_after_delay(300), wait=wait_fixed(30)):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 435, in __iter__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 368, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 411, in exc_check\n    raise retry_exc from fut.exception()\ntenacity.RetryError: RetryError[<Future at 0x7fa23d31c860 state=finished raised AssertionError>]","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1756519407044,"stop":1756519407045,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1756519407045,"stop":1756519407262,"duration":217},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1756519407045,"stop":1756519407045,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"charm","time":{"start":1756519407045,"stop":1756519407045,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"highly_available_cluster","time":{"start":1756519407262,"stop":1756519594832,"duration":187570},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"continuous_writes","time":{"start":1756519594832,"stop":1756519596874,"duration":2042},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1756519594832,"stop":1756519594832,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"credentials","time":{"start":1756519596875,"stop":1756519598899,"duration":2024},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Test to send SIGTERM to all units and then ensure that the cluster recovers.","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7fa23d31c860 state=finished raised AssertionError>]","statusTrace":"Traceback (most recent call last):\n  File \"/root/spread_project/tests/integration/high_availability/test_self_healing_stop_all.py\", line 62, in test_graceful_full_cluster_crash_test\n    await ensure_process_not_running(\n  File \"/root/spread_project/tests/integration/high_availability/high_availability_helpers.py\", line 576, in ensure_process_not_running\n    assert return_code != 0, (\n           ^^^^^^^^^^^^^^^^\nAssertionError: Process mysqld is still running with pid 877\n on unit mysql-k8s/0, container mysql\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n                                ^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/root/spread_project/tests/integration/high_availability/test_self_healing_stop_all.py\", line 59, in test_graceful_full_cluster_crash_test\n    for attempt in Retrying(stop=stop_after_delay(300), wait=wait_fixed(30)):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 435, in __iter__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 368, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 411, in exc_check\n    raise retry_exc from fut.exception()\ntenacity.RetryError: RetryError[<Future at 0x7fa23d31c860 state=finished raised AssertionError>]","steps":[],"attachments":[{"uid":"8f504c61aaa54eab","name":"log","source":"8f504c61aaa54eab.txt","type":"text/plain","size":21250}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"continuous_writes::finalizer","time":{"start":1756519961282,"stop":1756519962301,"duration":1019},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"credentials::finalizer","time":{"start":1756519961282,"stop":1756519961282,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"highly_available_cluster::finalizer","time":{"start":1756519962302,"stop":1756519962302,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail::0","time":{"start":1756519962302,"stop":1756519962302,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1756519962303,"stop":1756519962687,"duration":384},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1756519962688,"stop":1756519962688,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1756519962688,"stop":1756519962688,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1756519962688,"stop":1756519962688,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.high_availability"},{"name":"suite","value":"test_self_healing_stop_all"},{"name":"host","value":"pkrvmccyg1gnepe"},{"name":"thread","value":"18571-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.high_availability.test_self_healing_stop_all"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"2f11d77fda3a8f59","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[]}],"history":{"statistic":{"failed":0,"broken":8,"skipped":0,"passed":163,"unknown":10,"total":181},"items":[{"uid":"9cf04eda182f69de","reportUrl":"../3189//#testresult/9cf04eda182f69de","status":"passed","time":{"start":1756435529893,"stop":1756435847967,"duration":318074}},{"uid":"ca11af02b20e3f4a","reportUrl":"../3188//#testresult/ca11af02b20e3f4a","status":"passed","time":{"start":1756346661463,"stop":1756346997796,"duration":336333}},{"uid":"872b7a96de5428bb","reportUrl":"../3184//#testresult/872b7a96de5428bb","status":"passed","time":{"start":1756259721229,"stop":1756260058097,"duration":336868}},{"uid":"85281a667fc713d9","reportUrl":"../3175//#testresult/85281a667fc713d9","status":"passed","time":{"start":1756175841513,"stop":1756176143388,"duration":301875}},{"uid":"1867a292e07f6e7a","reportUrl":"../3171//#testresult/1867a292e07f6e7a","status":"passed","time":{"start":1756085843325,"stop":1756086131831,"duration":288506}},{"uid":"ccd5f6ae6a44e22d","reportUrl":"../3170//#testresult/ccd5f6ae6a44e22d","status":"passed","time":{"start":1756000641616,"stop":1756000931879,"duration":290263}},{"uid":"fe684127ffceadda","reportUrl":"../3169//#testresult/fe684127ffceadda","status":"passed","time":{"start":1755914061501,"stop":1755914407987,"duration":346486}},{"uid":"39e0a916a465e35f","reportUrl":"../3166//#testresult/39e0a916a465e35f","status":"unknown","time":{}},{"uid":"42d08df9a8ab0349","reportUrl":"../3161//#testresult/42d08df9a8ab0349","status":"passed","time":{"start":1755741681808,"stop":1755741978764,"duration":296956}},{"uid":"f6b0759c5dab8dd2","reportUrl":"../3152//#testresult/f6b0759c5dab8dd2","status":"passed","time":{"start":1755655006315,"stop":1755655367793,"duration":361478}},{"uid":"9b6a0803b3340ed4","reportUrl":"../3143//#testresult/9b6a0803b3340ed4","status":"passed","time":{"start":1755567568913,"stop":1755567904089,"duration":335176}},{"uid":"807c8a255e189969","reportUrl":"../3142//#testresult/807c8a255e189969","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7f071818f770 state=finished raised AssertionError>]","time":{"start":1755480985652,"stop":1755481345908,"duration":360256}},{"uid":"ac4b6824d3b19e5e","reportUrl":"../3140//#testresult/ac4b6824d3b19e5e","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7fc9e68848c0 state=finished raised AssertionError>]","time":{"start":1755309201624,"stop":1755309560591,"duration":358967}},{"uid":"c41e754bec800ab2","reportUrl":"../3139//#testresult/c41e754bec800ab2","status":"passed","time":{"start":1755221664097,"stop":1755221947684,"duration":283587}},{"uid":"2b026e0fd4dff2b9","reportUrl":"../3138//#testresult/2b026e0fd4dff2b9","status":"passed","time":{"start":1755136892864,"stop":1755137157732,"duration":264868}},{"uid":"bd1ac43d30a52317","reportUrl":"../3137//#testresult/bd1ac43d30a52317","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7fe9bd3d32f0 state=finished raised AssertionError>]","time":{"start":1755051382423,"stop":1755051731921,"duration":349498}},{"uid":"51a5d98255d6c045","reportUrl":"../3136//#testresult/51a5d98255d6c045","status":"passed","time":{"start":1754962623915,"stop":1754962987486,"duration":363571}},{"uid":"f329fe06cfd48641","reportUrl":"../3132//#testresult/f329fe06cfd48641","status":"passed","time":{"start":1754877569784,"stop":1754877900556,"duration":330772}},{"uid":"6a68b0a3e2f69969","reportUrl":"../3130//#testresult/6a68b0a3e2f69969","status":"unknown","time":{}},{"uid":"b37f0fd927da465","reportUrl":"../3129//#testresult/b37f0fd927da465","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7f41e8a76b70 state=finished raised AssertionError>]","time":{"start":1754703334066,"stop":1754703683742,"duration":349676}}]},"tags":["asyncio"]},"source":"26dd70d6830cc997.json","parameterValues":[]}