[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model concierge-microk8s:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHTunneler received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.high_availability.conftest:conftest.py:57 Deploying mysql-k8s and scaling to 3 units
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-k8s-0
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [allocating] waiting: installing agent
  mysql-k8s/1 [allocating] waiting: installing agent
  mysql-k8s/2 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] maintenance: installing charm software
  mysql-k8s/1 [executing] maintenance: installing charm software
  mysql-k8s/2 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [idle] waiting: waiting to get cluster primary from peers
  mysql-k8s/2 [executing] waiting: waiting to get cluster primary from peers
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [executing] active: 
  mysql-k8s/2 [executing] maintenance: joining the cluster
[32mINFO    [0m integration.high_availability.conftest:conftest.py:60 Deploying mysql-test-app
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-test-app-73
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: installing agent
[32mINFO    [0m integration.high_availability.conftest:conftest.py:63 Relating mysql-k8s with mysql-test-app
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: 
  mysql-test-app/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: 
  mysql-test-app/0 [idle] active: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:27 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:29 Starting continuous writes
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:268 Deploying Chaos Mesh
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:278 Ensure chaos mesh is ready
[32mINFO    [0m integration.conftest:conftest.py:30 Getting credentials for the MySQL cluster
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:35 Ensuring that there are 3 online mysql members
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:40 Ensuring that all instances have incrementing continuous writes
[32mINFO    [0m mysql.connector:authentication.py:66 package: mysql.connector.plugins
[32mINFO    [0m mysql.connector:authentication.py:67 plugin_name: caching_sha2_password
[32mINFO    [0m mysql.connector:authentication.py:71 AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=87 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=120 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=120 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=153 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=153 on unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=185 on unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:48 Creating networkchaos policy to isolate instance mysql-k8s/0 from the cluster
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:55 Wait until MySQL GR actually detects isolated instance
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:72 Ensure all units have incrementing continuous writes
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=440 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=440 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=440 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=440 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=440 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=440 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=440 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=440 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=454 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=454 on unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=486 on unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:77 Remove networkchaos policy isolating instance from cluster
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:81 Wait until returning instance enters recovery
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:85 Wait until returning instance become active
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:90 Wait until all units are online
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:95 Ensure isolated instance is now secondary
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:104 Ensure there are 3 online mysql members
[32mINFO    [0m integration.high_availability.test_self_healing_network_cut:test_self_healing_network_cut.py:109 Ensure all units have incrementing continuous writes
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=587 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=620 on unit mysql-k8s/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=620 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=652 on unit mysql-k8s/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:500 max_written_value=653 on unit mysql-k8s/2
[32mINFO    [0m integration.high_availability.conftest:conftest.py:45 Destroying chaos mesh
[32mINFO    [0m integration.high_availability.conftest:conftest.py:34 Clearing continuous writes
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.7    unsupported  01:39:07Z

App             Version                  Status  Scale  Charm           Channel      Rev  Address         Exposed  Message
mysql-k8s       8.0.41-0ubuntu0.22.04.1  active      3  mysql-k8s                      0  10.152.183.62   no       
mysql-test-app  0.0.2                    active      1  mysql-test-app  latest/edge   73  10.152.183.146  no       Last written value=644

Unit               Workload  Agent  Address       Ports  Message
mysql-k8s/0        active    idle   10.1.249.139         
mysql-k8s/1        active    idle   10.1.249.140         Primary
mysql-k8s/2*       active    idle   10.1.249.141         
mysql-test-app/0*  active    idle   10.1.249.142         Last written value=644

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-0: 01:38:07 ERROR unit.mysql-k8s/0.juju-log database-peers:2: Binlogs collector service does not exist
unit-mysql-k8s-0: 01:38:07 ERROR unit.mysql-k8s/0.juju-log database-peers:2: Failed to reconcile binlogs collection during peer relation event
unit-mysql-k8s-0: 01:38:08 ERROR unit.mysql-k8s/0.juju-log database-peers:2: Binlogs collector service does not exist
unit-mysql-k8s-0: 01:38:08 ERROR unit.mysql-k8s/0.juju-log database-peers:2: Failed to reconcile binlogs collection during peer relation event

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...