[32mINFO    [0m integration.test_tls:test_tls.py:218 Removing relation
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.5    unsupported  01:34:35Z

App                       Version                  Status  Scale  Charm                     Channel        Rev  Address         Exposed  Message
mysql-k8s                 8.0.37-0ubuntu0.22.04.3  active      3  mysql-k8s                                  0  10.152.183.206  no       
self-signed-certificates                           active      1  self-signed-certificates  latest/stable  155  10.152.183.32   no       

Unit                         Workload  Agent  Address      Ports  Message
mysql-k8s/0*                 active    idle   10.1.177.75         
mysql-k8s/1                  active    idle   10.1.177.77         
mysql-k8s/2                  active    idle   10.1.177.76         
self-signed-certificates/0*  active    idle   10.1.177.78         

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-0: 01:33:27 ERROR unit.mysql-k8s/0.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-1: 01:33:33 ERROR unit.mysql-k8s/1.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-0: 01:33:33 ERROR unit.mysql-k8s/0.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-2: 01:33:36 ERROR unit.mysql-k8s/2.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-1: 01:33:38 ERROR unit.mysql-k8s/1.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-0: 01:33:39 ERROR unit.mysql-k8s/0.juju-log certificates:3: An unknown certificate expiring.
unit-self-signed-certificates-0: 01:34:08 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "38cefe41-5d90-4fe3-8894-51302b0d81ea:r#3#mysql-k8s": settings 38cefe41-5d90-4fe3-8894-51302b0d81ea:r#3#mysql-k8s not found (not found)
unit-mysql-k8s-1: 01:34:10 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "38cefe41-5d90-4fe3-8894-51302b0d81ea:r#3#self-signed-certificates": settings 38cefe41-5d90-4fe3-8894-51302b0d81ea:r#3#self-signed-certificates not found (not found)

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...