{"uid":"3db87bc432b1a690","name":"test_crash_during_cluster_setup","fullName":"tests.integration.high_availability.test_crash_during_setup#test_crash_during_cluster_setup","historyId":"8f6187e014aaf86ae98aa86475a82995","time":{"start":1736731688511,"stop":1736732619268,"duration":930757},"status":"broken","statusMessage":"TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n    return await fut\n           ^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/juju/utils.py\", line 136, in _block\n    await asyncio.sleep(wait_period)\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 665, in sleep\n    return await future\n           ^^^^^^^^^^^^\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n                                ^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/tests/integration/high_availability/test_crash_during_setup.py\", line 55, in test_crash_during_cluster_setup\n    await ops_test.model.block_until(\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/juju/model.py\", line 1153, in block_until\n    await utils.block_until(done, timeout=timeout, wait_period=wait_period)\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/juju/utils.py\", line 138, in block_until\n    await asyncio.shield(asyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 519, in wait_for\n    async with timeouts.timeout(timeout):\n  File \"/usr/lib/python3.12/asyncio/timeouts.py\", line 115, in __aexit__\n    raise TimeoutError from exc_val\nTimeoutError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"ops_test","time":{"start":1736731688313,"stop":1736731688510,"duration":197},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1736731688313,"stop":1736731688313,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop","time":{"start":1736731688313,"stop":1736731688313,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1736731688511,"stop":1736731688511,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n    return await fut\n           ^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/juju/utils.py\", line 136, in _block\n    await asyncio.sleep(wait_period)\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 665, in sleep\n    return await future\n           ^^^^^^^^^^^^\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n                                ^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/tests/integration/high_availability/test_crash_during_setup.py\", line 55, in test_crash_during_cluster_setup\n    await ops_test.model.block_until(\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/juju/model.py\", line 1153, in block_until\n    await utils.block_until(done, timeout=timeout, wait_period=wait_period)\n  File \"/home/runner/work/mysql-k8s-operator/mysql-k8s-operator/.tox/integration/lib/python3.12/site-packages/juju/utils.py\", line 138, in block_until\n    await asyncio.shield(asyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.12/asyncio/tasks.py\", line 519, in wait_for\n    async with timeouts.timeout(timeout):\n  File \"/usr/lib/python3.12/asyncio/timeouts.py\", line 115, in __aexit__\n    raise TimeoutError from exc_val\nTimeoutError","steps":[],"attachments":[{"uid":"dc487b973086eb61","name":"log","source":"dc487b973086eb61.txt","type":"text/plain","size":1442}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1736732619273,"stop":1736732619273,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1736732619274,"stop":1736732619643,"duration":369},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1736732619644,"stop":1736732619644,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1736732619644,"stop":1736732619644,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1736732619644,"stop":1736732619644,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"group(1)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.high_availability"},{"name":"suite","value":"test_crash_during_setup"},{"name":"host","value":"fv-az1296-640"},{"name":"thread","value":"15856-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.high_availability.test_crash_during_setup"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"9f867a6b4a9673df","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":17,"skipped":0,"passed":84,"unknown":2,"total":103},"items":[{"uid":"b51cd1d5bfb8e6b4","reportUrl":"../2569//#testresult/b51cd1d5bfb8e6b4","status":"passed","time":{"start":1736645354550,"stop":1736645563861,"duration":209311}},{"uid":"65331777d1969e3a","reportUrl":"../2567//#testresult/65331777d1969e3a","status":"passed","time":{"start":1736558927968,"stop":1736559143023,"duration":215055}},{"uid":"d50509e7832e5b57","reportUrl":"../2562//#testresult/d50509e7832e5b57","status":"broken","statusDetails":"TimeoutError","time":{"start":1736472525278,"stop":1736473459958,"duration":934680}},{"uid":"a6f9dc108c14f6ba","reportUrl":"../2539//#testresult/a6f9dc108c14f6ba","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735867728533,"stop":1735868661223,"duration":932690}},{"uid":"6b47710c5c508e13","reportUrl":"../2538//#testresult/6b47710c5c508e13","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735781308735,"stop":1735782242081,"duration":933346}},{"uid":"16c70e2fec00eb0a","reportUrl":"../2537//#testresult/16c70e2fec00eb0a","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735694909099,"stop":1735695840626,"duration":931527}},{"uid":"f00e75deb5d5f5cf","reportUrl":"../2536//#testresult/f00e75deb5d5f5cf","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735608520306,"stop":1735609452657,"duration":932351}},{"uid":"cfdf218eb1c6d169","reportUrl":"../2534//#testresult/cfdf218eb1c6d169","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735522123934,"stop":1735523055809,"duration":931875}},{"uid":"3a026611c63b7338","reportUrl":"../2533//#testresult/3a026611c63b7338","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735435723953,"stop":1735436656473,"duration":932520}},{"uid":"525e7ad6e2719041","reportUrl":"../2532//#testresult/525e7ad6e2719041","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735349306866,"stop":1735350239047,"duration":932181}},{"uid":"2600b50ddf979cf0","reportUrl":"../2530//#testresult/2600b50ddf979cf0","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735262907428,"stop":1735263839089,"duration":931661}},{"uid":"f2c49e4ed9f11c67","reportUrl":"../2529//#testresult/f2c49e4ed9f11c67","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735176508411,"stop":1735177444142,"duration":935731}},{"uid":"86b847d3755d7084","reportUrl":"../2528//#testresult/86b847d3755d7084","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735090113503,"stop":1735091044322,"duration":930819}},{"uid":"47b10413c34a54f8","reportUrl":"../2526//#testresult/47b10413c34a54f8","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1735003701901,"stop":1735004632963,"duration":931062}},{"uid":"bd338fa8a6989a2e","reportUrl":"../2521//#testresult/bd338fa8a6989a2e","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1734917326055,"stop":1734918257957,"duration":931902}},{"uid":"6d50c62cfa92c12b","reportUrl":"../2520//#testresult/6d50c62cfa92c12b","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1734830923966,"stop":1734831855186,"duration":931220}},{"uid":"2d07ae233c0aeced","reportUrl":"../2519//#testresult/2d07ae233c0aeced","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1734744494554,"stop":1734745426684,"duration":932130}},{"uid":"2555e1dc77486bfc","reportUrl":"../2518//#testresult/2555e1dc77486bfc","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1734658119398,"stop":1734659053796,"duration":934398}},{"uid":"7171e134e6dde13a","reportUrl":"../2514//#testresult/7171e134e6dde13a","status":"passed","time":{"start":1734571730550,"stop":1734571937812,"duration":207262}},{"uid":"39e5d4b9b21a08c8","reportUrl":"../2507//#testresult/39e5d4b9b21a08c8","status":"passed","time":{"start":1734398933840,"stop":1734399154204,"duration":220364}}]},"tags":["asyncio","abort_on_fail","group(1)"]},"source":"3db87bc432b1a690.json","parameterValues":[]}